name: black
on:
  push:
    paths: ["problems/**.py", ".github/workflows/black.yml"]
  pull_request:
    paths: ["problems/**.py", ".github/workflows/black.yml"]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
