name: pytest-cocotb
on: [push, pull_request]
jobs:
  cocotb:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/builderdev212/cocotb-runner
      env: 
        actor: ${{ github.actor }}
    steps:
      - uses: actions/checkout@main
      - run: ls
      - run: pytest
  # cocotb:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3   
  #     - name: Run pytest
  #       uses: builderdev212/cocotb-runner
  #         run: pytest -n 10
  # container-test-job:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/builderdev212/cocotb-runner
  #     volumes:
  #       - my_docker_volume:/usr/src/verilogbits
  #   steps:
  #     - name: Check for dockerenv file
  #       run: cd /usr/src/verilogbits && pytest


# .docker_tmpl: &container_job
#    tags:
#      - podman-runner
#    image: cocotb-dev:latest

# ex:
#   <<: *container_job
#   rules:
#     - if: $CI_COMMIT_BRANCH
#       changes:
#         paths:
#   stage: test
#   script:
#     - cd 
#     - pytest -n 10 --retries 2

