name: pytest-cocotb
on: [push, pull_request]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/builderdev212/cocotb-runner
    steps:
      - name: Run testbenches
        run: pytest -n 10