name: pytest-cocotb
on: [push, pull_request]
jobs:
  cocotb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   
      - name: Run pytest
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/builderdev212/cocotb-runner:latest
          run: pytest -n 10