name: pytest-cocotb
on: [push, pull_request]
jobs:
  container-test-job:
    runs-on: debian:12-slim
    container: 
      image: ghcr.io/builderdev212/cocotb-runner
      volumes:
        - ${PWD}:/usr/src/verilogbits
    steps:
      - name: Run testbenches
        run: cd verilogbits && pytest -n 10